Add a nightly run of the test suite against chia-blockchain at main
Chia-Network/CAT-admin-tool pull request #39
Opened 2023-11-01 21:47 UTC by hoffmang9

2023-11-01 22:03 UTC, hoffmang9 commented
And another bug uncovered - this time it's in the in memory db test change - https://github.com/Chia-Network/chia-blockchain/pull/16637:
```
ImportError while loading conftest '/home/runner/work/CAT-admin-tool/CAT-admin-tool/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from chia.simulator.setup_nodes import setup_simulators_and_wallets_service
venv/lib/python3.10/site-packages/chia/simulator/setup_nodes.py:24: in <module>
    from chia.simulator.setup_services import (
venv/lib/python3.10/site-packages/chia/simulator/setup_services.py:57: in <module>
    from tests.util.db_connection import generate_in_memory_db_uri
E   ModuleNotFoundError: No module named 'tests'
Error: Process completed with exit code 4.
```

2023-11-09 09:28 UTC, AmineKhaldi commented
> And another bug uncovered - this time it's in the in memory db test change - [Chia-Network/chia-blockchain#16637](https://github.com/Chia-Network/chia-blockchain/pull/16637):
> 
> ```
> ImportError while loading conftest '/home/runner/work/CAT-admin-tool/CAT-admin-tool/tests/conftest.py'.
> tests/conftest.py:6: in <module>
>     from chia.simulator.setup_nodes import setup_simulators_and_wallets_service
> venv/lib/python3.10/site-packages/chia/simulator/setup_nodes.py:24: in <module>
>     from chia.simulator.setup_services import (
> venv/lib/python3.10/site-packages/chia/simulator/setup_services.py:57: in <module>
>     from tests.util.db_connection import generate_in_memory_db_uri
> E   ModuleNotFoundError: No module named 'tests'
> Error: Process completed with exit code 4.
> ```

I sent an addendum [PR #16752](https://github.com/Chia-Network/chia-blockchain/pull/16752), shortly after the [original PR #16637](https://github.com/Chia-Network/chia-blockchain/pull/16637), that should address this.

2023-12-14 20:45 UTC, cmmarslender requested changes

2023-12-14 20:45 UTC, cmmarslender commented on .github/workflows/nightly-against-main.yml
> +      max-parallel: 4
Unless doing a matrix, this doesn't really do much

2023-12-14 20:49 UTC, cmmarslender approved these changes

2023-12-14 20:57 UTC, wjblanke approved these changes
aok

2023-12-14 20:58 UTC, merged