Setup pre-commit and fix up source
Chia-Network/CAT-admin-tool pull request #54
Opened 2024-05-09 20:23 UTC by emlowe

Add pre-commit workflow
Matchup pre-commit version with setup.py
Add dev dependencies to setup.py

Modify source code to pass pre-commit checks

2024-05-09 21:03 UTC, Quexington approved these changes, later dismissed

2024-05-13 22:44 UTC, altendky requested changes

2024-05-13 22:44 UTC, altendky commented on .pre-commit-config.yaml
> +        exclude: ".*?(.hex|.clvm|.clib)"
https://github.com/Chia-Network/chia-blockchain/blob/bd3a638db10ee92a15f138ceaef06648c3c7b480/.pre-commit-config.yaml#L48

I don't recall the details around this...  but we might not want to get into them here.  Also, undo associated changes.

```suggestion
        exclude: ".*?(.hex|.clsp|.clvm|.clib)"
```

2024-05-20 19:26 UTC, altendky approved these changes

2024-05-20 19:37 UTC, merged